### ISSUE TITLE
Unable to get token using EZGetToken() || !TypeError

### ISSUE THREAD

**Issue by devLio1** [alamhamim/cypress-ez-lib#2]
Looked thru my code nothing wrong with my code. 
Getting this error.....

```
1
requestPOST 200 /auth/login
2
logObject{9}
3
thenfunction(){}
TypeError

  21 |   it("test: 1", function(){
  22 |     getToken(url, user, pass).then(function(token){
> 23 |       cy.log(token.access_token);
     |                    ^
  24 |       api.EZGet(token.access_token, url);
  25 |     })
  26 |   })


```

**Comment by alamhamim** [comment]
Looks like previous approach of the code does not support in latest version of cypress, so updated the source code also updated cypress to the latest version in the library. After the fix, ran multiple tests on latest version of cypress-ez-lib. Looks like fix is working. 

Released Version: cypress-ez-lib 1.0.9 (With minor bug fixes)

If you are using cypress-ez-lib already, I would suggest you update to the latest version.

Run: npm install cypress-ez-lib@1.0.9
